name: ilovlya
description: Ilovlya Media Center

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+9

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  app_links: ^3.4.3
  audio_video_progress_bar: ^1.0.1
  flutter:
    sdk: flutter
  flutter_in_app_pip: ^1.7.3
  flutter_localizations:
    sdk: flutter
  http: ^1.0.0
  json_annotation: ^4.8.1
  url_launcher: ^6.1.12
  video_player: ^2.7.0
  wakelock: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
