name: ilovlya
description: Ilovlya Media Center

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 2.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  app_links: ^6.0.2
  audio_service: ^0.18.13
  audio_video_progress_bar: ^2.0.2
  background_downloader: ^8.5.0
  device_info_plus: ^10.1.0
  duration: ^3.0.13
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  fvp: ^0.17.0
  google_fonts: ^6.2.1
  http: ^1.1.0
  idb_shim: ^2.3.2
  intl: any
  json_annotation: ^4.9.0
  media_kit: ^1.1.10+1
  media_kit_libs_video: ^1.0.4
  media_kit_video: ^1.2.4
  path: ^1.8.3
  path_provider: ^2.1.2
  riverpod_annotation: ^2.2.1
  share_plus: ^9.0.0
  shared_preferences: ^2.2.2
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.12
  video_player: ^2.7.2
  wakelock_plus: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.0
  riverpod_generator: ^2.3.5
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
